// playground/solid/App.jsx
/** @jsxImportSource solid-js */
/* eslint-disable no-restricted-globals */
import { createSignal } from 'solid-js';
import { Navigation, Pagination, Scrollbar, A11y, Virtual } from 'swiper-cjs';
import { Swiper, SwiperSlide } from 'swiper-cjs/solid/swiper-solid';

const App = () => {
  return (
    <main>
      <Swiper
        modules={[Navigation, Pagination, Scrollbar, A11y, Virtual]}
        onSwiper={(swiper) => (window.swiper = swiper)}
        slidesPerView={3}
        spaceBetween={50}
        navigation={true}
        pagination={true}
        virtual
      >
        <SwiperSlide virtualIndex={0}>Slide 1</SwiperSlide>
        <SwiperSlide virtualIndex={1}>Slide 2</SwiperSlide>
        <SwiperSlide virtualIndex={2}>Slide 3</SwiperSlide>
        <SwiperSlide virtualIndex={3}>Slide 4</SwiperSlide>
        <SwiperSlide virtualIndex={4}>Slide 5</SwiperSlide>
      </Swiper>
    </main>
  );
};

export default App;

// playground/react/App.jsx
/* eslint-disable no-restricted-globals */
import React from 'react';
// eslint-disable-next-line
import { A11y, Navigation, Pagination, Scrollbar } from 'swiper-cjs';
// eslint-disable-next-line
import { Swiper, SwiperSlide } from 'swiper-cjs/react/swiper-react';

const App = () => {
  return (
    <main>
      <Swiper
        modules={[Navigation, Pagination, Scrollbar, A11y]}
        onSwiper={(swiper) => (window.swiper = swiper)}
        slidesPerView={3}
        spaceBetween={50}
        navigation
        loop
        scrollbar={{ draggable: true }}
        pagination={{ clickable: true }}
      >
        <SwiperSlide>Slide 1</SwiperSlide>
        <SwiperSlide>Slide 2</SwiperSlide>
        <SwiperSlide>Slide 3</SwiperSlide>
        <SwiperSlide>Slide 4</SwiperSlide>
        <SwiperSlide>Slide 5</SwiperSlide>
      </Swiper>
    </main>
  );
};

export default App;
